export enum SimStatus {
  ACTIVE = 'ACTIVE',
  ACTIVATION_IN_PROGRESS = 'ACTIVATION_IN_PROGRESS',
  SUSPENDED = 'SUSPENDED',
  COMPLETED = 'COMPLETED',
  SIM_CARD_LOST = 'SIM_CARD_LOST',
  COLLECTION_BARRING = 'COLLECTION_BARRING',
}
