export enum QueryParamEnum {
  FLOW = 'flow',
  PGSTATUS = 'pgstatus',
  ITEM = 'item',
  PRODUCT_TYPE = 'producttype',
  SALES_ORDER_ID = 'sid',
  PRODUCT_IDENTIFIER = 'pid',
  STATUSES = 'statuses',
  INTENT = 'intent',
  SOURCE = 'source',
  SOURCE_NBA = 'nba',
  SOURCE_ITS_ME = 'itsme',
  SOURCE_EMAIL = 'email',
  VAL = 'val',
  SO_TOKEN = 'token',
  JWT_TOKEN = 'jwt',
  FLOW_MARKETING = 'marketing',
  IDENTIFIER = 'identifier',
  STEP = 'step',
  INTENT_SUFFIX = 'intentsuffix',
  ACTION = 'action',
  INSTALLATION_LOCATION_ID = 'installationLocationId',
  SDATA = 'sdata',
}
