variables:
  CLIENT_PROJECT: customer-web-billing-invoice-mfe
  LEANIX_APPLICATION_NAME: billing
  CLIENT_PROJECT_PATH: billing/invoice-mfe
  CLIENT_E2E: customer-web-billing-invoice-mfe-e2e
  V3_GITOPS_DEPLOY_FOLDER_NAME: billing/invoice
  GITOPS_DEPLOY_FOLDER_NAME: customer-web-billing/invoice

include:
  - local: '/tools/gitlab/base/application.yml'

test:app:
  extends: .test:app
  rules:
    - when: always

e2e:app:
  extends: .e2e:local
  rules:
    - when: always

build:app:
  extends: .build:app

build:storybook:
  extends: .build:storybook

push-to-harbor:
  extends: .push-to-harbor

component-test:app:
  extends: .component-test:app

sonar:app:
  extends: .sonar:app
  needs:
    - test:app
    - component-test:app

gitops-deploy-stage:
  extends: .gitops-deploy-stage
  only: !reference [.allowed-branches-feat-deploy]

gitops-deploy-upgrade:
  extends: .gitops-deploy-upgrade

gitops-deploy-prod:
  extends: .gitops-deploy-prod
  only: !reference [.allowed-branches-feat-deploy]

gitops-deploy-dev:
  extends: .gitops-deploy-dev

tag-stage-candidate:
  extends: .tag-stage-candidate
  only: !reference [.allowed-branches-feat-deploy]

tag-prod-candidate:
  extends: .tag-prod-candidate
  only: !reference [.allowed-branches-feat-deploy]

patch-stage:
  extends: .patch-stage

patch-prod:
  extends: .patch-prod

integration-test-int:
  extends: .e2e:integrated
  stage: deploy to dev (dvp, int, sup)
  variables:
    E2E_ENVIRONMENT: 'int'
  needs:
    - gitops-deploy-dev
  only: !reference [.allowed-branches-dev-deploy]
  when: on_success
  allow_failure: true
