/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UiOptions {
  /**
   * MFE name
   */
  mfeName: string;
  /**
   * Domain name
   */
  domain?: string;
  /**
   * LeanIX name
   */
  leanIxName: string;
  /**
   * For publishable libs: Official package name used in import statements
   */
  importPath?: string;
  [k: string]: unknown;
}
