export enum CreateFleetLineStepEnum {
  SIM_NUMBER = 'sim-number',
  IS_SPLIT_BILL = 'is-split-bill',
  IS_PROFILE_NEEDED = 'is-profile-needed',
  CREATE_PROFILE_FORM = 'create-profile-form',
  TARIFF_PLAN = 'tariff-plan',
  ADDRESS_FORM = 'address-form',
  DUPLICATE_CONTACTS = 'duplicate-contacts',
  TARIFF_PLAN_OPTIONS = 'tariff-plan-options',
  TARIFF_PLAN_OPTIONS_NONE_SELECTED = 'tariff-plan-options-none-selected',
  BILLING_ACCOUNT = 'billing-account',
  ACTIVATION_DATE = 'activation-date',
  NUMBER_OPTIONS = 'number-options',
  NUMBER_TYPES = 'number-types',
  PORTING_DETAILS_FORM = 'porting-details-form',
  RESERVE_NUMBER = 'reserve-number',
  SPLIT_BILL_PROFILE = 'split-bill-profile',
  SUBMIT_REVIEW = 'submit-review',
  UPLOAD_DOCUMENT = 'upload-document',
  NO_FILES_UPLOADED = 'info.no-documents-uploaded',
  INSTALLATION_ADDRESS = 'installationAddress',
}
