export enum ProductTypeEnum {
  MOBILE = 'MOBILE',
  OPTION = 'OPTION',
  SMARTPHONE = 'SMARTPHONE',
  SMARTPHONES = 'SMARTPHONES',
  INTERNET = 'INTERNET',
  DTV = 'DTV',
  TV = 'OTTV',
  FIXED_LINE = 'FIXED LINE',
  BUNDLE = 'BUNDLE',

  TELEPHONE = 'TELEPHONE',

  MOBILE_LINE = 'MOBILE LINE',
  PLACEHOLDER = 'PLACEHOLDER',

  PLUME = 'PLUME',
}
