/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DataAccessOptions {
  /**
   * Should a facade be generated
   */
  facade?: boolean;
  /**
   * LeanIX name
   */
  leanIxName: string;
  /**
   * MFE name
   */
  mfeName: string;
  /**
   * Domainname
   */
  domain?: string;
  [k: string]: unknown;
}
