export enum ShoppingBasketEnum {
  HARDWARE,
  MOBILE,
  INTERNET,
}

export enum SalesOrderState {
  INITIALIZED,
  SALES_ORDER_CREATED,
  ORDER_ITEMS_ADDED,
  ETF_NEEDED,
  ETF_HANDLED,
  INSTALLATION_CONFIGURED,
  APPOINTMENT_CONFIGURED,
  DELIVERY_CALCULATED,
  DELIVERY_ADDRESS_CHANGED,
  CONTRACT_SUMMARY_GENERATED,
  CHECKOUT_DELIVERY_FINISHED,
  SALES_ORDER_SUBMITTED,
  PAYMENT_TRANSACTION_CREATED,
  INGENICO_FORM_SET,
  PAYMENT_SUCCESSFUL,
  PAYMENT_CANCELLED,
  SERVICEABILITY_CHECKED,
}

export enum StepNameEnum {
  INSTALLATION_ADDRESS,
  ETF,
  MOBILE_CONFIGURATION,
  FIXED_TELEPHONY,
  MIGRATION,
  INSTALLATION_TYPE,
  APPOINTMENT,
  DELIVERY,
  EASY_SWITCH,
  SUMMARY,
  CONFIRMATION,
}
