export enum AppActionEnum {
  INITIALISE_CUSTOMER,
}

export enum StateActionEnum {
  EMPTY,
  CREATE_SALES_ORDER,
  SET_SERVICEABILITY,
  SET_ABANDONABLE,
  CHECK_SERVICEABILITY,
  GET_CUSTOMER_ID,
  ADD_ORDER_ITEMS,
  SET_SALES_ORDER_ABANDONABLE,
}
