export enum ProductTypeEnum {
  MOBILE = 'MOBILE',
  OPTION = 'OPTION',
  SMARTPHONE = 'SMARTPHONE',
  SMARTPHONES = 'SMARTPHONES',
  INTERNET = 'INTERNET',
  DTV = 'DTV',
  TV = 'OTTV',
  BUNDLE = 'BUNDLE',
  MOBILE_LINE = 'MOBILE LINE',
  PLACEHOLDER = 'PLACEHOLDER',
  DOMAIN_NAME = 'DOMAIN NAME',
}
