import { ModuleWithProviders, NgModule, Provider } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { CommonModule, DatePipe } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { MatMomentDateModule } from '@angular/material-moment-adapter';
import { InlineSVGConfig, InlineSVGModule } from 'ng-inline-svg-2';
import {
  AbstractCheckboxComponent,
  AbstractDateOfBirthPickerComponent,
  AbstractDropdownComponent,
  AbstractInputRadioWithInputComponent,
  AbstractRadioCheckboxComponent,
  AbstractRadioComponent,
  DateOfBirthPickerComponent,
  DateOfBirthPickerWithDropdownInputComponent,
  DatepickerComponent,
  DropdownComponent,
  DropDownWithChipsComponent,
  DropdownWithInputComponent,
  DropdownWithTooltipComponent,
  DuidComponent,
  InputAbstractComponent,
  InputAppointmentDatePickerComponent,
  InputAppointmentMomentPickerComponent,
  InputAppointmentPickerByDateComponent,
  InputAppointmentPickerByMomentComponent,
  InputAppointmentPickerComponent,
  InputAtomicComponent,
  InputCheckboxComponent,
  InputCheckboxDefaultComponent,
  InputCheckboxLegalComponent,
  InputCheckboxWithCardComponent,
  InputComponent,
  InputWithTooltipComponent,
  InputDatePickerComponent,
  InputMomentPickerComponent,
  InputNewAppointmentPickerComponent,
  InputRadioCardComponent,
  InputRadioComponent,
  InputRadioDefaultComponent,
  InputRadioGroupCardComponent,
  InputRadioHorizontalComponent,
  InputRadioImageComponent,
  InputRadioIconComponent,
  InputRadioWithCardAndPriceComponent,
  InputRadioWithCardComponent,
  InputRadioWithCardMiniNoSelectBoxLabelsComponent,
  InputRadioWithCardMiniWithSelectBoxLabelsComponent,
  InputRadioWithInputHorizontalComponent,
  InputRadioWithInputVerticalComponent,
  MACAddressComponent,
  MatMultipleSelectWithInputComponent,
  MatSelectWithInputComponent,
  MonthDropdownComponent,
  NoAvailableAppointmentDateComponent,
  NewNoAvailableAppointmentDateComponent,
  InputRadioCardRadioRightComponent,
} from './controls';
import { FormDirective, FormErrorService, MessageGroupDirective } from './errors';
import { AppointmentPickerObjectPipe, AppointmentPickerPipe, EuroSignPipe, PricePipe, TimeslotPipe } from './pipes';
import {
  AutoHeightDirective,
  ButtonClickDirective,
  ClickPreventDefaultDirective,
  ClickStopPropagationDirective,
  ColDirective,
  ContainerDirective,
  ContainerPartitionDirective,
  EventLinkClickDirective,
  FontColorDirective,
  FontFamilyDirective,
  FontSizeDirective,
  FontWeightDirective,
  FullWidthDirective,
  IconDirective,
  LoadPageDirective,
  MarginDirective,
  MatchHeightDirective,
  PaddingDirective,
  RowDirective,
  ScrollFocusInvalidInputDirective,
  ScrollToErrorDirective,
  TextDecorationDirective,
  TextFlowDirective,
  TrackBlurEventDirective,
  TrackingInfoDirective,
  TrackInputEventDirective,
  WhitespaceDirective,
} from './directives';
import { AppointmentPickerValidator } from './validators';
import { PriceService, SvgConfig } from './services';
import { InstallTypePriceComponent } from './components';
import { MatInputModule } from '@angular/material/input';
import { ImageSrcPathModule } from '@telenet/ng-lib-page';
import { NgxMaskDirective, NgxMaskPipe, provideEnvironmentNgxMask } from 'ngx-mask';
import { MatSelectModule } from '@angular/material/select';
import { SlickCarouselModule } from 'ngx-slick-carousel';

export const FORMS_PROVIDERS = [
  InputAbstractComponent,
  AbstractDropdownComponent,
  AbstractDateOfBirthPickerComponent,
  AbstractRadioCheckboxComponent,
  DatePipe,
  AppointmentPickerPipe,
  TimeslotPipe,
  FormErrorService,
  AppointmentPickerValidator,
  provideEnvironmentNgxMask(),
  PriceService,
] as Provider[];

@NgModule({
  imports: [
    CommonModule,
    TranslateModule,
    ReactiveFormsModule,
    FormsModule,
    ImageSrcPathModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatMomentDateModule,
    InlineSVGModule,
    NgxMaskDirective,
    NgxMaskPipe,
    MatInputModule,
    SlickCarouselModule,
    MatSelectModule,
    PricePipe,
    EuroSignPipe,
  ],
  declarations: [
    InputAbstractComponent,
    AppointmentPickerPipe,
    AppointmentPickerObjectPipe,
    TimeslotPipe,
    AbstractDropdownComponent,
    AbstractDateOfBirthPickerComponent,
    InputAppointmentPickerComponent,
    InputAppointmentPickerByDateComponent,
    InputAppointmentPickerByMomentComponent,
    InputAppointmentDatePickerComponent,
    InputAppointmentMomentPickerComponent,
    InputComponent,
    InputWithTooltipComponent,
    InputAtomicComponent,
    InputRadioImageComponent,
    InputRadioIconComponent,
    InputRadioComponent,
    AbstractRadioComponent,
    AbstractRadioCheckboxComponent,
    InputRadioDefaultComponent,
    InputRadioHorizontalComponent,
    InputRadioWithCardComponent,
    InputRadioWithCardAndPriceComponent,
    InputRadioWithCardMiniNoSelectBoxLabelsComponent,
    InputRadioWithCardMiniWithSelectBoxLabelsComponent,
    AbstractInputRadioWithInputComponent,
    InputRadioWithInputHorizontalComponent,
    InputRadioWithInputVerticalComponent,
    AbstractCheckboxComponent,
    InputCheckboxComponent,
    InputCheckboxDefaultComponent,
    InputCheckboxWithCardComponent,
    InputCheckboxLegalComponent,
    FormDirective,
    DropdownComponent,
    DropdownWithInputComponent,
    DropDownWithChipsComponent,
    MatMultipleSelectWithInputComponent,
    MatSelectWithInputComponent,
    DropdownWithTooltipComponent,
    DateOfBirthPickerWithDropdownInputComponent,
    MonthDropdownComponent,
    InputRadioCardComponent,
    InputRadioGroupCardComponent,
    DatepickerComponent,
    MessageGroupDirective,
    DateOfBirthPickerComponent,
    ScrollToErrorDirective,
    InputMomentPickerComponent,
    InputDatePickerComponent,
    InputNewAppointmentPickerComponent,
    MarginDirective,
    RowDirective,
    TextFlowDirective,
    InstallTypePriceComponent,
    PaddingDirective,
    FontSizeDirective,
    FontFamilyDirective,
    FontWeightDirective,
    FontColorDirective,
    ButtonClickDirective,
    IconDirective,
    EventLinkClickDirective,
    TrackBlurEventDirective,
    TrackInputEventDirective,
    TrackingInfoDirective,
    ContainerDirective,
    ContainerPartitionDirective,
    ColDirective,
    FullWidthDirective,
    LoadPageDirective,
    WhitespaceDirective,
    AutoHeightDirective,
    ClickPreventDefaultDirective,
    ClickStopPropagationDirective,
    MatchHeightDirective,
    ScrollFocusInvalidInputDirective,
    MACAddressComponent,
    TextDecorationDirective,
    DuidComponent,
    NoAvailableAppointmentDateComponent,
    NewNoAvailableAppointmentDateComponent,
    InputRadioCardRadioRightComponent,
  ],
  exports: [
    MarginDirective,
    RowDirective,
    TextFlowDirective,
    InputAbstractComponent,
    AbstractDropdownComponent,
    AbstractDateOfBirthPickerComponent,
    InputAppointmentPickerComponent,
    InputAppointmentPickerByDateComponent,
    InputAppointmentPickerByMomentComponent,
    InputAppointmentDatePickerComponent,
    InputAppointmentMomentPickerComponent,
    InputComponent,
    InputAtomicComponent,
    InputWithTooltipComponent,
    InputRadioImageComponent,
    InputRadioIconComponent,
    InputRadioComponent,
    AbstractRadioComponent,
    AbstractRadioCheckboxComponent,
    InputRadioDefaultComponent,
    InputRadioHorizontalComponent,
    InputRadioWithCardComponent,
    AbstractCheckboxComponent,
    InputCheckboxComponent,
    InputCheckboxDefaultComponent,
    InputCheckboxWithCardComponent,
    InputCheckboxLegalComponent,
    InputRadioWithCardMiniNoSelectBoxLabelsComponent,
    InputRadioWithCardMiniWithSelectBoxLabelsComponent,
    AbstractInputRadioWithInputComponent,
    InputRadioWithInputHorizontalComponent,
    InputRadioWithInputVerticalComponent,
    FormDirective,
    AppointmentPickerPipe,
    AppointmentPickerObjectPipe,
    TimeslotPipe,
    DropdownComponent,
    DropdownWithInputComponent,
    DropdownWithTooltipComponent,
    DateOfBirthPickerWithDropdownInputComponent,
    InputRadioCardComponent,
    InputRadioGroupCardComponent,
    DatepickerComponent,
    MessageGroupDirective,
    DateOfBirthPickerComponent,
    ScrollToErrorDirective,
    InputNewAppointmentPickerComponent,
    InputDatePickerComponent,
    InputMomentPickerComponent,
    DropDownWithChipsComponent,
    MatMultipleSelectWithInputComponent,
    MatSelectWithInputComponent,
    InputRadioWithCardAndPriceComponent,
    TranslateModule,
    InstallTypePriceComponent,
    PaddingDirective,
    FontSizeDirective,
    FontFamilyDirective,
    FontWeightDirective,
    FontColorDirective,
    ButtonClickDirective,
    IconDirective,
    EventLinkClickDirective,
    TrackBlurEventDirective,
    TrackInputEventDirective,
    TrackingInfoDirective,
    ContainerDirective,
    ContainerPartitionDirective,
    ColDirective,
    FullWidthDirective,
    LoadPageDirective,
    WhitespaceDirective,
    AutoHeightDirective,
    ClickPreventDefaultDirective,
    ClickStopPropagationDirective,
    MatchHeightDirective,
    ScrollFocusInvalidInputDirective,
    MACAddressComponent,
    TextDecorationDirective,
    DuidComponent,
    NoAvailableAppointmentDateComponent,
    NewNoAvailableAppointmentDateComponent,
    InputRadioCardRadioRightComponent,
  ],
  providers: FORMS_PROVIDERS,
})
export class TgFormsModule {
  static forRoot(imagePath: string): ModuleWithProviders<TgFormsModule> {
    return {
      ngModule: TgFormsModule,
      providers: [
        ...FORMS_PROVIDERS,
        { provide: 'IMAGE_BASE_PATH', useValue: imagePath },
        { provide: InlineSVGConfig, useClass: SvgConfig },
      ],
    };
  }
}
