export enum ValidationElementEnum {
  FEASIBILITY_CHECK_REQUIRED = 'FEASIBILITY_CHECK_REQUIRED',
  CHECKOUT_DELIVERY_REQUIRED = 'DELIVERY_CHECKOUT_REQUIRED',
  CUSTOMER_INFO_NOT_FILLED = 'CUSTOMER_INFO_NOT_FILLED',
}
