import { Product } from '../entities/models/product.model';

enum CATEGORY {
  FOR_RULES_2_ND_HOME_PROMO_MANUAL = 'for-rules---2nd-home-promo-manual',
  FOR_RULES_FOR_129521_DISCOUNT = 'for-rules---for-129521-discount',
  FOR_RULES_125420_PROMO = 'for-rules---125420-promo',
  FOR_RULES_2_P_BUNDLES_FOR_649 = 'for-rules---2p-bundles-for-649',
  FOR_RULES_874_PROMO = 'for-rules---874-promo',
  FOR_RULES_TLOS_WITH_TELENET_TV_1_0 = 'for-rules---tlos-with-telenet-tv-1-0',
  FOR_DISCOUNTS_874_PROMO = 'for-discounts---874-promo',
  FOR_RULES_FOR_110620_DISCOUNT = 'for-rules---for-110620-discount',
  FOR_RULES_PARTNER_DISCOUNT_EXCEPT_ONEUP = 'for-rules---partner-discount-except-oneup',
  FOR_RULES_453_EXTERNE_MEDEWERKERS_KORTING = 'for-rules---453-externe-medewerkers-korting',
  FOR_RULES_OFFERINGS_FOR_107800 = 'for-rules---offerings-for-107800',
  FOR_DISCOUNTS_FOR_120800_AND_120820 = 'for-discounts---for-120800-and-120820',
  FOR_DISCOUNTS_782_PROMO = 'for-discounts---782-promo',
  FOR_DISCOUNT_2_ND_HOME_PROMO_3_P_BUNDLES_INTERNET = 'for-discount---2nd-home-promo-3p-bundles--internet',
  FOR_RULES_TLOS_WITH_SPEEDBOOST = 'for-rules---tlos-with-speedboost',
  FOR_RULES_4_P_2_P_1_P_PLANS_WHERE_SAFESPOT_IS_PAYABLE = 'for-rules---4p2p1p-plans-where-safespot-is-payable',
  FOR_RULES_2_P_BUNDLES = 'for-rules---2p-bundles',
  FOR_DISCOUNT_121810_PROMO = 'for-discount---121810-promo',
  FOR_RULES_TOP_OFFERING_WITH_SERVICE_POLICIES = 'for-rules----top-offering-with-service-policies',
  FOR_RULES_WIGO_FOR_126941 = 'for-rules---wigo-for-126941',
  FOR_DISCOUNT_2_P_3_P_BUNDLES_INTERNET = 'for-discount---2p3p-bundles--internet',
  FOR_RULES_TV_ICONIC_FLOW_ONLY = 'for-rules---tv-iconic--flow-only',
  STAFF_DISCOUNT_FURIOUS_WITH_FIXED_LINE_NEW_OFFERING = 'staff-discount-furious-with-fixed-line-new-offering',
  FOR_RULES_WIGOONEUP_BUNDLES = 'for-rules---wigooneup-bundles',
  FOR_DISCOUNTS_159_PROMO = 'for-discounts---159-promo',
  FOR_RULES_PARTNER_DISCOUNT = 'for-rules---partner-discount',
  FOR_DISCOUNTS_117200_PROMO = 'for-discounts---117200-promo',
  FOR_RULES_115810_ONLY = 'for-rules---115810-only',
  FOR_DISCOUNTS_132941_PROMO = 'for-discounts---132941-promo',
  FOR_DISCOUNT_GROUP_DISCOUNT_MANUAL = 'for-discount---group-discount-manual',
  FOR_RULES_RES_DIGITAL_TV_AND_BUNDLES_WITH_DIGITAL_TV = 'for-rules---res-digital-tv-and-bundles-with-digital-tv',
  FOR_RULES_ALL_INTERNET_TV_WIGO_FOR_100650 = 'for-rules---all-internet--tv-wigo-for-100650',
  FOR_RULES_139331_PROMO = 'for-rules---139331-promo',
  FOR_RULES_649_ONLY = 'for-rules---649-only',
  FOR_RULES_TLOS_FOR_3_TB_FUP_INTERNET_SERVICE_POLICIES = 'for-rules--tlos-for-3tb-fup-internet-service-policies',
  FOR_RULES_RES_BUNDLES = 'for-rules---res-bundles',
  FOR_DISCOUNTS_133331_PROMO = 'for-discounts---133331-promo',
  FOR_SPONSOR_DISCOUNT_ALL_TLO_PRODUCTS = 'for-sponsor-discount---all-tlo-products',
  FOR_DISCOUNT_FOR_107020_DISCOUNTS = 'for-discount---for-107020-discounts',
  FOR_DISCOUNTS_26_PROMO = 'for-discounts---26-promo',
  FOR_RULES_ALL_INTERNET_TV_WIGO = 'for-rules---all-internet--tv-wigo',
  FOR_RULES_PRICE_REDUCTION_DURING_3_MONTHS = 'for-rules---price-reduction-during-3-months',
  FOR_RULES_FOR_112721_DISCOUNT = 'for-rules---for-112721-discount',
  FOR_RULES_FIXED_AND_BUNDLES_CATEGORY = 'for-rules---fixed-and-bundles-category',
  FOR_RULES_ALL_INTERNET_TELENET_TV_ICONIC_ALL_INTERNET_TELENET_TV_FLOW_ONE_FOR_X_ONEUP_FOR_X = 'for-rules---all-internet--telenet-tv-iconic--all-internet--telenet-tv-flow--one-for-x--oneup-for-x',
  FOR_RULES_OFFERINGS_FOR_120531 = 'for-rules---offerings-for-120531',
  FOR_RULES_SUBSCRIPTION_CABLE_TV = 'for-rules--subscription-cable-tv',
  FOR_RULES_2_P_BUNDLES_INTERNET_IDTV = 'for-rules---2p-bundles-internet-idtv',
  FOR_RULES_FREE_ACTIVATION_PROMO = 'for-rules---free-activation-promo',
  _2P_BUNDLE = '2p-bundle',
  FOR_RULES_MULTI_DTV_PROMO = 'for-rules---multi-dtv-promo',
  FOR_RULES_2_P_1_P_PLANS_WHERE_SAFESPOT_IS_PAYABLE = 'for-rules---2p1p-plans-where-safespot-is-payable',
  FOR_RULES_PARTNER_DISCOUNT_ONEUP_WITH_FIXED_LINE = 'for-rules---partner-discount-oneup-with-fixed-line',
  FOR_RULES_FOR_124951_DISCOUNT = 'for-rules---for-124951-discount',
  FOR_RULES_FOR_107020_DISCOUNTS = 'for-rules---for-107020-discounts',
  FOR_RULES_DISCOUNTED_OFFERINGS_FOR_107800 = 'for-rules---discounted-offerings-for-107800',
  FOR_RULES_ALL_INTERNET_INTERNET_FIBER_200 = 'for-rules---all-internet-internet-fiber-200',
  FOR_RULES_875_DISCOUNT = 'for-rules---875-discount',
  FOR_RULES_139601_PROMO = 'for-rules---139601-promo',
  FOR_RULES_141321_INT_LINES = 'for-rules---141321-int-lines',
  FOR_RULES_9_PERSONEELSKORTING_TELENET = 'for-rules---9-personeelskorting-telenet',
  POST_PAID_MOBILE = 'post-paid-mobile',
}
const WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS = 'watch-live-and-delayed-tv-on-33-channels';
const ONBEPERKT_SURFEN = 'Onbeperkt surfen';
const SPEC_FIXEDINTERNET_VOLUME_DOWNLOAD_FUP = 'spec-fixedinternet-volume-download-fup';
const SPEC_FIXEDINTERNET_MAILBOX_INCLUDED = 'spec-fixedinternet-mailbox-included';
const ALL_INTERNET_LOGO =
  'https://customerzone.prd.base.be/content/dam/www-base-be/img/self-service/products/all-internet-+-telenet-tv-iconic.png';
const ALL_INTERNET_TELENET_TV = 'All-Internet + Telenet TV';
const RECURRENT_CHARGE = 'Recurrent Charge';
const INTERNET_DTV = 'Internet+DTV';
const INTERNET_SERVICE_LOGO =
  'https://customerzone.prd.base.be/content/dam/www-base-be/img/self-service/products/internet-service.png';
const IDDTV_ACCESS_LOGO =
  'https://customerzone.prd.base.be/content/dam/www-base-be/img/self-service/products/idtv-access-(sipadan).png';
const DTV_SIPADAN_TYPE = 'dtv[SIPADAN]';
const ALL_INTERNET_TELENET_TVICONIC_LABEL = 'All-Internet + Telenet TV Iconic';
const PRODUCTION_TEST = 'production-test';
const DOWNLOADSNELHEID_TOT = 'Downloadsnelheid: tot';
const THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY = 'the-best-local-and-international-series-with-play';
const AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS = 'automatically-save-programs-for-up-to-60-days';
const SPEC_FIXEDINTERNET_SPEED_UPLOAD = 'spec-fixedinternet-speed-upload';
const UPLOADSNELHEID_TOT = 'Uploadsnelheid: tot';
const SPEC_FIXEDINTERNET_SPEED_DOWNLOAD = 'spec-fixedinternet-speed-download';
const WATCH_TV_BACK_UP_TO_7_DAYS = 'watch-tv-back-up-to-7-days';
const WATCH_TV_BACK_UP = 'Watch TV back up';
const PER_MAILBOX = 'per mailbox';
const SPEC_FIXEDINTERNET_MAILBOX_VOLUME = 'spec-fixedinternet-mailbox-volume';
export class ProductTestfactory {
  getProductsMockWithBundle(): Product[] {
    return [
      {
        isC5Bundle(): boolean {
          return false;
        },
        children: [
          {
            isProductActivationInProgress(): boolean {
              return false;
            },
            isProductDisconnectionInProgress(): boolean {
              return false;
            },
            isProductModificationInProgress(): boolean {
              return false;
            },
            isProductSuspended(): boolean {
              return false;
            },
            isProductActive(): boolean {
              return true;
            },
            id: '9167320892413189785',
            productInfo: {
              isShowRates(): boolean {
                return false;
              },
              getSortedSpecifications() {
                return [
                  {
                    labelKey: SPEC_FIXEDINTERNET_VOLUME_DOWNLOAD_FUP,
                    unit: 'GB',
                    value: 'unlimited',
                    visible: true,
                    weight: '10',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: ONBEPERKT_SURFEN,
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: true,
                  },
                  {
                    labelKey: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                    visible: true,
                    weight: '20',
                    productType: 'DTV',
                    localizedContent: {
                      locale: 'nl',
                      name: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                    },
                    serviceType: 'DTV',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: false,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: SPEC_FIXEDINTERNET_MAILBOX_VOLUME,
                    unit: 'GB',
                    value: '5',
                    visible: true,
                    weight: '20',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: PER_MAILBOX,
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: true,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: WATCH_TV_BACK_UP_TO_7_DAYS,
                    visible: true,
                    weight: '40',
                    productType: 'DTV',
                    localizedContent: {
                      locale: 'nl',
                      name: WATCH_TV_BACK_UP,
                    },
                    serviceType: 'DTV',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: false,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: SPEC_FIXEDINTERNET_SPEED_DOWNLOAD,
                    unit: 'Mbps',
                    value: '300',
                    visible: true,
                    weight: '40',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: DOWNLOADSNELHEID_TOT,
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: true,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                    visible: true,
                    weight: '50',
                    productType: 'DTV',
                    localizedContent: {
                      locale: 'nl',
                      name: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                    },
                    serviceType: 'DTV',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: false,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: SPEC_FIXEDINTERNET_SPEED_UPLOAD,
                    unit: 'Mbps',
                    value: '20',
                    visible: true,
                    weight: '50',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: UPLOADSNELHEID_TOT,
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: true,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                    visible: true,
                    weight: '60',
                    productType: 'DTV',
                    localizedContent: {
                      locale: 'nl',
                      name: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                    },
                    serviceType: 'DTV',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: false,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: SPEC_FIXEDINTERNET_MAILBOX_INCLUDED,
                    value: '10',
                    visible: true,
                    weight: '60',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: 'mailboxen',
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: true,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                ];
              },
              internalCategory: CATEGORY.POST_PAID_MOBILE,
              productId: 'TWOP0013',
              isYupProduct: false,
              externalProductCode: 'TWOP0013',
              productType: 'BUNDLE',
              categories: [
                ...[
                  CATEGORY.FOR_RULES_2_ND_HOME_PROMO_MANUAL,
                  CATEGORY.FOR_RULES_FOR_129521_DISCOUNT,
                  CATEGORY.FOR_RULES_125420_PROMO,
                  CATEGORY.FOR_RULES_2_P_BUNDLES_FOR_649,
                  CATEGORY.FOR_RULES_874_PROMO,
                  CATEGORY.FOR_RULES_TLOS_WITH_TELENET_TV_1_0,
                  CATEGORY.FOR_DISCOUNTS_874_PROMO,
                  CATEGORY.FOR_RULES_FOR_110620_DISCOUNT,
                  CATEGORY.FOR_RULES_PARTNER_DISCOUNT_EXCEPT_ONEUP,
                  CATEGORY.FOR_RULES_453_EXTERNE_MEDEWERKERS_KORTING,
                  CATEGORY.FOR_RULES_OFFERINGS_FOR_107800,
                  CATEGORY.FOR_DISCOUNTS_FOR_120800_AND_120820,
                  CATEGORY.FOR_DISCOUNTS_782_PROMO,
                  CATEGORY.FOR_DISCOUNT_2_ND_HOME_PROMO_3_P_BUNDLES_INTERNET,
                  CATEGORY.FOR_RULES_TLOS_WITH_SPEEDBOOST,
                  CATEGORY.FOR_RULES_4_P_2_P_1_P_PLANS_WHERE_SAFESPOT_IS_PAYABLE,
                  CATEGORY.FOR_RULES_2_P_BUNDLES,
                  CATEGORY.FOR_DISCOUNT_121810_PROMO,
                  CATEGORY.FOR_RULES_TOP_OFFERING_WITH_SERVICE_POLICIES,
                  CATEGORY.FOR_RULES_WIGO_FOR_126941,
                  CATEGORY.FOR_DISCOUNT_2_P_3_P_BUNDLES_INTERNET,
                  CATEGORY.FOR_RULES_TV_ICONIC_FLOW_ONLY,
                  CATEGORY.STAFF_DISCOUNT_FURIOUS_WITH_FIXED_LINE_NEW_OFFERING,
                  CATEGORY.FOR_RULES_WIGOONEUP_BUNDLES,
                  CATEGORY.FOR_DISCOUNTS_159_PROMO,
                  CATEGORY.FOR_RULES_PARTNER_DISCOUNT,
                  CATEGORY.FOR_DISCOUNTS_117200_PROMO,
                  CATEGORY.FOR_RULES_115810_ONLY,
                  CATEGORY.FOR_DISCOUNTS_132941_PROMO,
                  CATEGORY.FOR_DISCOUNT_GROUP_DISCOUNT_MANUAL,
                  CATEGORY.FOR_RULES_RES_DIGITAL_TV_AND_BUNDLES_WITH_DIGITAL_TV,
                  CATEGORY.FOR_RULES_ALL_INTERNET_TV_WIGO_FOR_100650,
                  CATEGORY.FOR_RULES_139331_PROMO,
                  CATEGORY.FOR_RULES_649_ONLY,
                  CATEGORY.FOR_RULES_TLOS_FOR_3_TB_FUP_INTERNET_SERVICE_POLICIES,
                  CATEGORY.FOR_RULES_RES_BUNDLES,
                  CATEGORY.FOR_DISCOUNTS_133331_PROMO,
                  CATEGORY.FOR_SPONSOR_DISCOUNT_ALL_TLO_PRODUCTS,
                  CATEGORY.FOR_DISCOUNT_FOR_107020_DISCOUNTS,
                  CATEGORY.FOR_DISCOUNTS_26_PROMO,
                  CATEGORY.FOR_RULES_ALL_INTERNET_TV_WIGO,
                  CATEGORY.FOR_RULES_PRICE_REDUCTION_DURING_3_MONTHS,
                  CATEGORY.FOR_RULES_FOR_112721_DISCOUNT,
                  CATEGORY.FOR_RULES_FIXED_AND_BUNDLES_CATEGORY,
                  CATEGORY.FOR_RULES_ALL_INTERNET_TELENET_TV_ICONIC_ALL_INTERNET_TELENET_TV_FLOW_ONE_FOR_X_ONEUP_FOR_X,
                  CATEGORY.FOR_RULES_OFFERINGS_FOR_120531,
                  CATEGORY.FOR_RULES_SUBSCRIPTION_CABLE_TV,
                  CATEGORY.FOR_RULES_2_P_BUNDLES_INTERNET_IDTV,
                  CATEGORY.FOR_RULES_FREE_ACTIVATION_PROMO,
                  CATEGORY._2P_BUNDLE,
                  CATEGORY.FOR_RULES_MULTI_DTV_PROMO,
                  CATEGORY.FOR_RULES_2_P_1_P_PLANS_WHERE_SAFESPOT_IS_PAYABLE,
                  CATEGORY.FOR_RULES_PARTNER_DISCOUNT_ONEUP_WITH_FIXED_LINE,
                  CATEGORY.FOR_RULES_FOR_124951_DISCOUNT,
                  CATEGORY.FOR_RULES_FOR_107020_DISCOUNTS,
                  CATEGORY.FOR_RULES_DISCOUNTED_OFFERINGS_FOR_107800,
                  CATEGORY.FOR_RULES_ALL_INTERNET_INTERNET_FIBER_200,
                  CATEGORY.FOR_RULES_875_DISCOUNT,
                  CATEGORY.FOR_RULES_139601_PROMO,
                  CATEGORY.FOR_RULES_141321_INT_LINES,
                  CATEGORY.FOR_RULES_9_PERSONEELSKORTING_TELENET,
                  CATEGORY.POST_PAID_MOBILE,
                ],
              ],
              customerCategories: ['residential', 'eventdemo', PRODUCTION_TEST],
              subCategory: {},
              labelKey: ALL_INTERNET_TELENET_TVICONIC_LABEL,
              visible: true,
              weight: 370,
              services: [
                {
                  serviceType: 'DTV',
                  specifications: [
                    {
                      labelKey: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                      visible: true,
                      weight: '20',
                      productType: 'DTV',
                      localizedContent: {
                        locale: 'nl',
                        name: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                      },
                    },
                    {
                      labelKey: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                      visible: true,
                      weight: '60',
                      productType: 'DTV',
                      localizedContent: {
                        locale: 'nl',
                        name: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                      },
                    },
                    {
                      labelKey: WATCH_TV_BACK_UP_TO_7_DAYS,
                      visible: true,
                      weight: '40',
                      productType: 'DTV',
                      localizedContent: {
                        locale: 'nl',
                        name: WATCH_TV_BACK_UP,
                      },
                    },
                    {
                      labelKey: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                      visible: true,
                      weight: '50',
                      productType: 'DTV',
                      localizedContent: {
                        locale: 'nl',
                        name: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                      },
                    },
                  ],
                  experience: {
                    experienceType: 'ENTERTAINMENT',
                  },
                },
                {
                  serviceType: 'FIXED_INTERNET',
                  specifications: [
                    {
                      labelKey: SPEC_FIXEDINTERNET_VOLUME_DOWNLOAD_FUP,
                      unit: 'GB',
                      value: 'unlimited',
                      visible: true,
                      weight: '10',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: ONBEPERKT_SURFEN,
                      },
                    },
                    {
                      labelKey: SPEC_FIXEDINTERNET_SPEED_DOWNLOAD,
                      unit: 'Mbps',
                      value: '300',
                      visible: true,
                      weight: '40',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: DOWNLOADSNELHEID_TOT,
                      },
                    },
                    {
                      labelKey: SPEC_FIXEDINTERNET_MAILBOX_VOLUME,
                      unit: 'GB',
                      value: '5',
                      visible: true,
                      weight: '20',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: PER_MAILBOX,
                      },
                    },
                    {
                      labelKey: SPEC_FIXEDINTERNET_SPEED_UPLOAD,
                      unit: 'Mbps',
                      value: '20',
                      visible: true,
                      weight: '50',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: UPLOADSNELHEID_TOT,
                      },
                    },
                    {
                      labelKey: SPEC_FIXEDINTERNET_MAILBOX_INCLUDED,
                      value: '10',
                      visible: true,
                      weight: '60',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: 'mailboxen',
                      },
                    },
                  ],
                  experience: {
                    experienceType: 'SURF',
                  },
                },
              ],
              apps: [],
              localizedContent: [
                {
                  locale: 'en',
                  name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
                  logo: ALL_INTERNET_LOGO,
                },
                {
                  locale: 'nl',
                  name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
                  logo: ALL_INTERNET_LOGO,
                },
                {
                  locale: 'fr',
                  name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
                  logo: ALL_INTERNET_LOGO,
                },
              ],
              shortDescription: {
                localizedContent: {
                  locale: 'nl',
                  name: ALL_INTERNET_TELENET_TV,
                },
              },
              visibilityRules: {
                conditionalVisibility: false,
              },
              unlimited: false,
              eligibleForDiscount: false,
              priceType: RECURRENT_CHARGE,
              characteristics: {
                serviceCategory: 'FUP',
                productGroup: 'FMC',
                productSubGroup: INTERNET_DTV,
                productSegment: 'RMD',
                priceInclVat: 74,
                recipientsMandatory: false,
                esimAvailable: false,
              },
              usageBasedRatePlan: false,
              requiresInstallation: true,
              chars: [
                {
                  key: 'internet_usage_limit',
                  values: ['3000'],
                  unit: 'GB',
                },
                {
                  key: 'internet_usage_initial_threshold',
                  values: ['2400'],
                  unit: 'GB',
                },
                {
                  key: 'internet_usage_alert_threshold',
                  values: ['2700'],
                  unit: 'GB',
                },
              ],
              isExternalContentPack: 'false',
              isEligibleForSettinglimits: false,
              isEligibleForAutoPause: false,
              isEligibleForPauseProfile: false,
              isFPBProduct: false,
              name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
              logo: ALL_INTERNET_LOGO,
              usageLimits: {
                premiumService: {
                  preferenceGroup: 'PremiumServices',
                  limits: [
                    {
                      communicationPreferenceType: 'OutBundleFraud',
                      communicationPreferenceTypeValue: 'NA',
                      isEditable: false,
                      values: [],
                    },
                    {
                      communicationPreferenceType: 'OutBundlePremiumSpendingLimit',
                      communicationPreferenceTypeValue: 'NA',
                      isEditable: false,
                      values: [],
                    },
                  ],
                },
              },
              usagenotifications: {
                mobile: [],
                internet: [
                  {
                    category: 'FUP',
                    preferenceGroup: 'InternetFUP',
                    threshold: [
                      {
                        communicationPreferenceType: 'Internet90',
                        communicationPreferenceTypeValue: '90',
                        isEditable: false,
                        values: [],
                      },
                      {
                        communicationPreferenceType: 'Internet100',
                        communicationPreferenceTypeValue: '100',
                        isEditable: false,
                        values: [],
                      },
                    ],
                  },
                ],
              },
              productConstituents: [
                {
                  type: DTV_SIPADAN_TYPE,
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: DTV_SIPADAN_TYPE,
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: DTV_SIPADAN_TYPE,
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: DTV_SIPADAN_TYPE,
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'dtv[EOS]',
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'dtv[EOS]',
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'dtv[EOS]',
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'dtv[EOS]',
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'internet_line',
                  minCount: '1',
                  maxCount: '1',
                },
              ],
            },
            handsets: [],
            productType: 'internet',
            addressId: '9165638478413166537',
            identifier: 'INT000063582',
            hasIncludedOptions: false,
            options: [],
            hasExtraOptions: false,
            label: 'Internet Service',
            productSpec: {
              internalCategory: CATEGORY.POST_PAID_MOBILE,
              productId: 'INLN0001',
              isYupProduct: false,
              externalProductCode: 'INLN0001',
              productType: 'INTERNET LINE',
              categories: [
                'for-rules---intenet-technical-lines',
                'for-rules---technical-line-slos',
                'for-rules---technical-line-slostv-equipmentmbp',
                'for-rules---products-for-installation-fee',
                'for-rules---lines-for-discount-slot',
                'for-rules---mbp-digital-products',
                'for-rules---fixed-interactive-product',
                'for-rules---bundle-tlos-technical-lines-for-res-and-b2b',
                'for-rules---internet-service--tv-acces-for-2p-bundles',
                'for-rules---res-products-for-mailbox',
                'for-rules---fixed-interactive-product-res--b2b',
                'for-rules---fixed-interactive-product-res--b2b-with-tv-lines',
                'for-rules---fixed-interactive-product-res-with-tv-lines',
                'for-rules---fixed-interactive-product-res--b2b-with-all-tv-lines',
                'for-rules---fixed-interactive-product-res-with-all-tv-lines',
                'for-rules---fixeddtvinternst-accesses',
                'for-rules---products-with-activation-trigger-char-c-res--b2b',
                'for-rules---products-with-tech-workaround-sale-char-c-res--b2b',
                'for-rules---fixed-technical-lines-resb2b',
              ],
              customerCategories: ['residential', 'eventdemo', PRODUCTION_TEST],
              subCategory: {},
              labelKey: 'Internet Service',
              visible: true,
              weight: 10,
              services: [
                {
                  serviceType: 'FIXED_INTERNET',
                  specifications: [],
                  experience: {
                    experienceType: 'SURF',
                  },
                },
              ],
              apps: [],
              localizedContent: [
                {
                  locale: 'en',
                  name: 'Internet',
                  logo: INTERNET_SERVICE_LOGO,
                },
                {
                  locale: 'nl',
                  name: 'Internet',
                  logo: INTERNET_SERVICE_LOGO,
                },
                {
                  locale: 'fr',
                  name: 'Internet',
                  logo: INTERNET_SERVICE_LOGO,
                },
              ],
              shortDescription: {},
              visibilityRules: {
                conditionalVisibility: false,
              },
              unlimited: false,
              eligibleForDiscount: false,
              priceType: RECURRENT_CHARGE,
              characteristics: {
                productGroup: 'OTHER',
                productSubGroup: '',
                productSegment: 'RMD',
                priceInclVat: 0,
                recipientsMandatory: false,
                esimAvailable: false,
              },
              usageBasedRatePlan: false,
              requiresInstallation: false,
              isExternalContentPack: 'false',
              isEligibleForSettinglimits: false,
              isEligibleForAutoPause: false,
              isEligibleForPauseProfile: false,
              isFPBProduct: false,
              name: 'Internet',
              logo: INTERNET_SERVICE_LOGO,
            },
            status: 'ACTIVE',
            bundleMaxlines: null,
          },
          {
            isProductActivationInProgress(): boolean {
              return false;
            },
            isProductDisconnectionInProgress(): boolean {
              return false;
            },
            isProductModificationInProgress(): boolean {
              return false;
            },
            isProductSuspended(): boolean {
              return false;
            },
            isProductActive(): boolean {
              return true;
            },
            id: '9167320897313189785',
            productInfo: {
              isShowRates(): boolean {
                return false;
              },
              getSortedSpecifications() {
                return [
                  {
                    labelKey: SPEC_FIXEDINTERNET_VOLUME_DOWNLOAD_FUP,
                    unit: 'GB',
                    value: 'unlimited',
                    visible: true,
                    weight: '10',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: ONBEPERKT_SURFEN,
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: true,
                  },
                  {
                    labelKey: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                    visible: true,
                    weight: '20',
                    productType: 'DTV',
                    localizedContent: {
                      locale: 'nl',
                      name: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                    },
                    serviceType: 'DTV',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: false,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: SPEC_FIXEDINTERNET_MAILBOX_VOLUME,
                    unit: 'GB',
                    value: '5',
                    visible: true,
                    weight: '20',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: PER_MAILBOX,
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: true,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: WATCH_TV_BACK_UP_TO_7_DAYS,
                    visible: true,
                    weight: '40',
                    productType: 'DTV',
                    localizedContent: {
                      locale: 'nl',
                      name: WATCH_TV_BACK_UP,
                    },
                    serviceType: 'DTV',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: false,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: SPEC_FIXEDINTERNET_SPEED_DOWNLOAD,
                    unit: 'Mbps',
                    value: '300',
                    visible: true,
                    weight: '40',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: DOWNLOADSNELHEID_TOT,
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: true,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                    visible: true,
                    weight: '50',
                    productType: 'DTV',
                    localizedContent: {
                      locale: 'nl',
                      name: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                    },
                    serviceType: 'DTV',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: false,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: SPEC_FIXEDINTERNET_SPEED_UPLOAD,
                    unit: 'Mbps',
                    value: '20',
                    visible: true,
                    weight: '50',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: UPLOADSNELHEID_TOT,
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: true,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                    visible: true,
                    weight: '60',
                    productType: 'DTV',
                    localizedContent: {
                      locale: 'nl',
                      name: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                    },
                    serviceType: 'DTV',
                    id: 'TWOP0013',
                    showUnit: false,
                    isValue: false,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                  {
                    labelKey: SPEC_FIXEDINTERNET_MAILBOX_INCLUDED,
                    value: '10',
                    visible: true,
                    weight: '60',
                    productType: 'INTERNET',
                    localizedContent: {
                      locale: 'nl',
                      name: 'mailboxen',
                    },
                    serviceType: 'FIXED_INTERNET',
                    id: 'TWOP0013',
                    showUnit: true,
                    isValue: true,
                    isMonetary: false,
                    isRange: false,
                    isAsterisk: false,
                  },
                ];
              },
              internalCategory: CATEGORY.POST_PAID_MOBILE,
              productId: 'TWOP0013',
              isYupProduct: false,
              externalProductCode: 'TWOP0013',
              productType: 'BUNDLE',
              categories: [
                CATEGORY.FOR_RULES_2_ND_HOME_PROMO_MANUAL,
                CATEGORY.FOR_RULES_FOR_129521_DISCOUNT,
                CATEGORY.FOR_RULES_125420_PROMO,
                CATEGORY.FOR_RULES_2_P_BUNDLES_FOR_649,
                CATEGORY.FOR_RULES_874_PROMO,
                CATEGORY.FOR_RULES_TLOS_WITH_TELENET_TV_1_0,
                CATEGORY.FOR_DISCOUNTS_874_PROMO,
                CATEGORY.FOR_RULES_FOR_110620_DISCOUNT,
                CATEGORY.FOR_RULES_PARTNER_DISCOUNT_EXCEPT_ONEUP,
                CATEGORY.FOR_RULES_453_EXTERNE_MEDEWERKERS_KORTING,
                CATEGORY.FOR_RULES_OFFERINGS_FOR_107800,
                CATEGORY.FOR_DISCOUNTS_FOR_120800_AND_120820,
                CATEGORY.FOR_DISCOUNTS_782_PROMO,
                CATEGORY.FOR_DISCOUNT_2_ND_HOME_PROMO_3_P_BUNDLES_INTERNET,
                CATEGORY.FOR_RULES_TLOS_WITH_SPEEDBOOST,
                CATEGORY.FOR_RULES_4_P_2_P_1_P_PLANS_WHERE_SAFESPOT_IS_PAYABLE,
                CATEGORY.FOR_RULES_2_P_BUNDLES,
                CATEGORY.FOR_DISCOUNT_121810_PROMO,
                CATEGORY.FOR_RULES_TOP_OFFERING_WITH_SERVICE_POLICIES,
                CATEGORY.FOR_RULES_WIGO_FOR_126941,
                CATEGORY.FOR_DISCOUNT_2_P_3_P_BUNDLES_INTERNET,
                CATEGORY.FOR_RULES_TV_ICONIC_FLOW_ONLY,
                CATEGORY.STAFF_DISCOUNT_FURIOUS_WITH_FIXED_LINE_NEW_OFFERING,
                CATEGORY.FOR_RULES_WIGOONEUP_BUNDLES,
                CATEGORY.FOR_DISCOUNTS_159_PROMO,
                CATEGORY.FOR_RULES_PARTNER_DISCOUNT,
                CATEGORY.FOR_DISCOUNTS_117200_PROMO,
                CATEGORY.FOR_RULES_115810_ONLY,
                CATEGORY.FOR_DISCOUNTS_132941_PROMO,
                CATEGORY.FOR_DISCOUNT_GROUP_DISCOUNT_MANUAL,
                CATEGORY.FOR_RULES_RES_DIGITAL_TV_AND_BUNDLES_WITH_DIGITAL_TV,
                CATEGORY.FOR_RULES_ALL_INTERNET_TV_WIGO_FOR_100650,
                CATEGORY.FOR_RULES_139331_PROMO,
                CATEGORY.FOR_RULES_649_ONLY,
                CATEGORY.FOR_RULES_TLOS_FOR_3_TB_FUP_INTERNET_SERVICE_POLICIES,
                CATEGORY.FOR_RULES_RES_BUNDLES,
                CATEGORY.FOR_DISCOUNTS_133331_PROMO,
                CATEGORY.FOR_SPONSOR_DISCOUNT_ALL_TLO_PRODUCTS,
                CATEGORY.FOR_DISCOUNT_FOR_107020_DISCOUNTS,
                CATEGORY.FOR_DISCOUNTS_26_PROMO,
                CATEGORY.FOR_RULES_ALL_INTERNET_TV_WIGO,
                CATEGORY.FOR_RULES_PRICE_REDUCTION_DURING_3_MONTHS,
                CATEGORY.FOR_RULES_FOR_112721_DISCOUNT,
                CATEGORY.FOR_RULES_FIXED_AND_BUNDLES_CATEGORY,
                CATEGORY.FOR_RULES_ALL_INTERNET_TELENET_TV_ICONIC_ALL_INTERNET_TELENET_TV_FLOW_ONE_FOR_X_ONEUP_FOR_X,
                CATEGORY.FOR_RULES_OFFERINGS_FOR_120531,
                CATEGORY.FOR_RULES_SUBSCRIPTION_CABLE_TV,
                CATEGORY.FOR_RULES_2_P_BUNDLES_INTERNET_IDTV,
                CATEGORY.FOR_RULES_FREE_ACTIVATION_PROMO,
                CATEGORY._2P_BUNDLE,
                CATEGORY.FOR_RULES_MULTI_DTV_PROMO,
                CATEGORY.FOR_RULES_2_P_1_P_PLANS_WHERE_SAFESPOT_IS_PAYABLE,
                CATEGORY.FOR_RULES_PARTNER_DISCOUNT_ONEUP_WITH_FIXED_LINE,
                CATEGORY.FOR_RULES_FOR_124951_DISCOUNT,
                CATEGORY.FOR_RULES_FOR_107020_DISCOUNTS,
                CATEGORY.FOR_RULES_DISCOUNTED_OFFERINGS_FOR_107800,
                CATEGORY.FOR_RULES_ALL_INTERNET_INTERNET_FIBER_200,
                CATEGORY.FOR_RULES_875_DISCOUNT,
                CATEGORY.FOR_RULES_139601_PROMO,
                CATEGORY.FOR_RULES_141321_INT_LINES,
                CATEGORY.FOR_RULES_9_PERSONEELSKORTING_TELENET,
                CATEGORY.POST_PAID_MOBILE,
              ],
              customerCategories: ['residential', 'eventdemo', PRODUCTION_TEST],
              subCategory: {},
              labelKey: ALL_INTERNET_TELENET_TVICONIC_LABEL,
              visible: true,
              weight: 370,
              services: [
                {
                  serviceType: 'DTV',
                  specifications: [
                    {
                      labelKey: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                      visible: true,
                      weight: '20',
                      productType: 'DTV',
                      localizedContent: {
                        locale: 'nl',
                        name: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                      },
                    },
                    {
                      labelKey: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                      visible: true,
                      weight: '60',
                      productType: 'DTV',
                      localizedContent: {
                        locale: 'nl',
                        name: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                      },
                    },
                    {
                      labelKey: WATCH_TV_BACK_UP_TO_7_DAYS,
                      visible: true,
                      weight: '40',
                      productType: 'DTV',
                      localizedContent: {
                        locale: 'nl',
                        name: WATCH_TV_BACK_UP,
                      },
                    },
                    {
                      labelKey: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                      visible: true,
                      weight: '50',
                      productType: 'DTV',
                      localizedContent: {
                        locale: 'nl',
                        name: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                      },
                    },
                  ],
                  experience: {
                    experienceType: 'ENTERTAINMENT',
                  },
                },
                {
                  serviceType: 'FIXED_INTERNET',
                  specifications: [
                    {
                      labelKey: SPEC_FIXEDINTERNET_VOLUME_DOWNLOAD_FUP,
                      unit: 'GB',
                      value: 'unlimited',
                      visible: true,
                      weight: '10',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: ONBEPERKT_SURFEN,
                      },
                    },
                    {
                      labelKey: SPEC_FIXEDINTERNET_SPEED_DOWNLOAD,
                      unit: 'Mbps',
                      value: '300',
                      visible: true,
                      weight: '40',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: DOWNLOADSNELHEID_TOT,
                      },
                    },
                    {
                      labelKey: SPEC_FIXEDINTERNET_MAILBOX_VOLUME,
                      unit: 'GB',
                      value: '5',
                      visible: true,
                      weight: '20',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: PER_MAILBOX,
                      },
                    },
                    {
                      labelKey: SPEC_FIXEDINTERNET_SPEED_UPLOAD,
                      unit: 'Mbps',
                      value: '20',
                      visible: true,
                      weight: '50',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: UPLOADSNELHEID_TOT,
                      },
                    },
                    {
                      labelKey: SPEC_FIXEDINTERNET_MAILBOX_INCLUDED,
                      value: '10',
                      visible: true,
                      weight: '60',
                      productType: 'INTERNET',
                      localizedContent: {
                        locale: 'nl',
                        name: 'mailboxen',
                      },
                    },
                  ],
                  experience: {
                    experienceType: 'SURF',
                  },
                },
              ],
              apps: [],
              localizedContent: [
                {
                  locale: 'en',
                  name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
                  logo: ALL_INTERNET_LOGO,
                },
                {
                  locale: 'nl',
                  name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
                  logo: ALL_INTERNET_LOGO,
                },
                {
                  locale: 'fr',
                  name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
                  logo: ALL_INTERNET_LOGO,
                },
              ],
              shortDescription: {
                localizedContent: {
                  locale: 'nl',
                  name: ALL_INTERNET_TELENET_TV,
                },
              },
              visibilityRules: {
                conditionalVisibility: false,
              },
              unlimited: false,
              eligibleForDiscount: false,
              priceType: RECURRENT_CHARGE,
              characteristics: {
                serviceCategory: 'FUP',
                productGroup: 'FMC',
                productSubGroup: INTERNET_DTV,
                productSegment: 'RMD',
                priceInclVat: 74,
                recipientsMandatory: false,
                esimAvailable: false,
              },
              usageBasedRatePlan: false,
              requiresInstallation: true,
              chars: [
                {
                  key: 'internet_usage_limit',
                  values: ['3000'],
                  unit: 'GB',
                },
                {
                  key: 'internet_usage_initial_threshold',
                  values: ['2400'],
                  unit: 'GB',
                },
                {
                  key: 'internet_usage_alert_threshold',
                  values: ['2700'],
                  unit: 'GB',
                },
              ],
              isExternalContentPack: 'false',
              isEligibleForSettinglimits: false,
              isEligibleForAutoPause: false,
              isEligibleForPauseProfile: false,
              isFPBProduct: false,
              name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
              logo: ALL_INTERNET_LOGO,
              usageLimits: {
                premiumService: {
                  preferenceGroup: 'PremiumServices',
                  limits: [
                    {
                      communicationPreferenceType: 'OutBundleFraud',
                      communicationPreferenceTypeValue: 'NA',
                      isEditable: false,
                      values: [],
                    },
                    {
                      communicationPreferenceType: 'OutBundlePremiumSpendingLimit',
                      communicationPreferenceTypeValue: 'NA',
                      isEditable: false,
                      values: [],
                    },
                  ],
                },
              },
              usagenotifications: {
                mobile: [],
                internet: [
                  {
                    category: 'FUP',
                    preferenceGroup: 'InternetFUP',
                    threshold: [
                      {
                        communicationPreferenceType: 'Internet90',
                        communicationPreferenceTypeValue: '90',
                        isEditable: false,
                        values: [],
                      },
                      {
                        communicationPreferenceType: 'Internet100',
                        communicationPreferenceTypeValue: '100',
                        isEditable: false,
                        values: [],
                      },
                    ],
                  },
                ],
              },
              productConstituents: [
                {
                  type: DTV_SIPADAN_TYPE,
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: DTV_SIPADAN_TYPE,
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: DTV_SIPADAN_TYPE,
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: DTV_SIPADAN_TYPE,
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'dtv[EOS]',
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'dtv[EOS]',
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'dtv[EOS]',
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'dtv[EOS]',
                  minCount: '0',
                  maxCount: '1',
                },
                {
                  type: 'internet_line',
                  minCount: '1',
                  maxCount: '1',
                },
              ],
            },
            handsets: [],
            productType: 'dtv',
            addressId: '9165638478413166537',
            identifier: 'DTV000025139',
            hasIncludedOptions: false,
            options: [],
            hasExtraOptions: false,
            label: 'iDTV access (Sipadan)',
            productSpec: {
              internalCategory: CATEGORY.POST_PAID_MOBILE,
              productId: 'TSIP0001',
              isYupProduct: false,
              externalProductCode: 'TSIP0001',
              productType: 'IDTV LINE',
              categories: [
                'for-rules---atvdtvidtv',
                'for-rules---idtv-accessessipadan-for-stb-update',
                'for-rules---technical-line-slos',
                'for-rules---dtv-lines',
                'for-rules---lines-for-discount-slot',
                'for-rules---technical-line-slostv-equipmentmbp',
                'for-rules---idtv-accesses-under-tv-and-bundles',
                'for-rules---mbp-digital-products',
                'for-rules---bundle-tlos-technical-lines-for-res-and-b2b',
                'for-rules---idtv',
                'for-rules---internet-service--tv-acces-for-2p-bundles',
                'for-rules---idtv-access-eossipadan',
                'for-rules---res-products-for-mailbox',
                'for-rules---idtv-accessessipadan',
                'for-rules---fixed-interactive-product-res--b2b-with-tv-lines',
                'for-rules---fixed-interactive-product-res-with-tv-lines',
                'for-rules---fixed-interactive-product-res--b2b-with-all-tv-lines',
                'for-rules---fixed-interactive-product-res-with-all-tv-lines',
                'for-rules---idtv-sipadan-resb2b',
                'for-rules---fixed-technical-lines-resb2b',
                'for-rules---res-idtv-accesses',
                'for-rules---res-idtv-and-ott-accesses',
                'for-rules---res-and-b2b-idtv-access-eossipadan',
              ],
              customerCategories: [
                'all',
                'residential',
                'production-test-business',
                'internal',
                PRODUCTION_TEST,
                'eventdemo',
                'business',
              ],
              subCategory: {},
              labelKey: 'iDTV access (Sipadan)',
              visible: true,
              weight: 40,
              services: [
                {
                  serviceType: 'DTV',
                  specifications: [],
                  experience: {
                    experienceType: 'ENTERTAINMENT',
                  },
                },
              ],
              apps: [],
              localizedContent: [
                {
                  locale: 'en',
                  name: 'Digital TV access',
                  logo: IDDTV_ACCESS_LOGO,
                },
                {
                  locale: 'nl',
                  name: 'Toegang digitale tv',
                  logo: IDDTV_ACCESS_LOGO,
                },
                {
                  locale: 'fr',
                  name: 'Accès TV digitale',
                  logo: IDDTV_ACCESS_LOGO,
                },
              ],
              shortDescription: {},
              visibilityRules: {
                conditionalVisibility: false,
              },
              unlimited: false,
              eligibleForDiscount: false,
              priceType: RECURRENT_CHARGE,
              characteristics: {
                productGroup: 'OTHER',
                productSubGroup: '',
                productSegment: 'ALL',
                priceInclVat: 0,
                recipientsMandatory: false,
                esimAvailable: false,
              },
              usageBasedRatePlan: false,
              requiresInstallation: true,
              maxCount: '1',
              isExternalContentPack: 'false',
              isEligibleForSettinglimits: false,
              isEligibleForAutoPause: false,
              isEligibleForPauseProfile: false,
              isFPBProduct: false,
              name: 'Toegang digitale tv',
              logo: IDDTV_ACCESS_LOGO,
              productConstituents: [],
            },
            status: 'ACTIVE',
            bundleMaxlines: null,
          },
        ],
        bundleType: INTERNET_DTV,
        productInfo: {
          hasCategory(): boolean {
            return false;
          },
          getSortedSpecifications() {
            return [
              {
                labelKey: SPEC_FIXEDINTERNET_VOLUME_DOWNLOAD_FUP,
                unit: 'GB',
                value: 'unlimited',
                visible: true,
                weight: '10',
                productType: 'INTERNET',
                localizedContent: {
                  locale: 'nl',
                  name: ONBEPERKT_SURFEN,
                },
                serviceType: 'FIXED_INTERNET',
                id: 'TWOP0013',
                showUnit: false,
                isValue: true,
                isMonetary: false,
                isRange: false,
                isAsterisk: true,
              },
              {
                labelKey: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                visible: true,
                weight: '20',
                productType: 'DTV',
                localizedContent: {
                  locale: 'nl',
                  name: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                },
                serviceType: 'DTV',
                id: 'TWOP0013',
                showUnit: false,
                isValue: false,
                isMonetary: false,
                isRange: false,
                isAsterisk: false,
              },
              {
                labelKey: SPEC_FIXEDINTERNET_MAILBOX_VOLUME,
                unit: 'GB',
                value: '5',
                visible: true,
                weight: '20',
                productType: 'INTERNET',
                localizedContent: {
                  locale: 'nl',
                  name: PER_MAILBOX,
                },
                serviceType: 'FIXED_INTERNET',
                id: 'TWOP0013',
                showUnit: true,
                isValue: true,
                isMonetary: false,
                isRange: false,
                isAsterisk: false,
              },
              {
                labelKey: WATCH_TV_BACK_UP_TO_7_DAYS,
                visible: true,
                weight: '40',
                productType: 'DTV',
                localizedContent: {
                  locale: 'nl',
                  name: WATCH_TV_BACK_UP,
                },
                serviceType: 'DTV',
                id: 'TWOP0013',
                showUnit: false,
                isValue: false,
                isMonetary: false,
                isRange: false,
                isAsterisk: false,
              },
              {
                labelKey: SPEC_FIXEDINTERNET_SPEED_DOWNLOAD,
                unit: 'Mbps',
                value: '300',
                visible: true,
                weight: '40',
                productType: 'INTERNET',
                localizedContent: {
                  locale: 'nl',
                  name: DOWNLOADSNELHEID_TOT,
                },
                serviceType: 'FIXED_INTERNET',
                id: 'TWOP0013',
                showUnit: true,
                isValue: true,
                isMonetary: false,
                isRange: false,
                isAsterisk: false,
              },
              {
                labelKey: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                visible: true,
                weight: '50',
                productType: 'DTV',
                localizedContent: {
                  locale: 'nl',
                  name: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                },
                serviceType: 'DTV',
                id: 'TWOP0013',
                showUnit: false,
                isValue: false,
                isMonetary: false,
                isRange: false,
                isAsterisk: false,
              },
              {
                labelKey: SPEC_FIXEDINTERNET_SPEED_UPLOAD,
                unit: 'Mbps',
                value: '20',
                visible: true,
                weight: '50',
                productType: 'INTERNET',
                localizedContent: {
                  locale: 'nl',
                  name: UPLOADSNELHEID_TOT,
                },
                serviceType: 'FIXED_INTERNET',
                id: 'TWOP0013',
                showUnit: true,
                isValue: true,
                isMonetary: false,
                isRange: false,
                isAsterisk: false,
              },
              {
                labelKey: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                visible: true,
                weight: '60',
                productType: 'DTV',
                localizedContent: {
                  locale: 'nl',
                  name: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                },
                serviceType: 'DTV',
                id: 'TWOP0013',
                showUnit: false,
                isValue: false,
                isMonetary: false,
                isRange: false,
                isAsterisk: false,
              },
              {
                labelKey: SPEC_FIXEDINTERNET_MAILBOX_INCLUDED,
                value: '10',
                visible: true,
                weight: '60',
                productType: 'INTERNET',
                localizedContent: {
                  locale: 'nl',
                  name: 'mailboxen',
                },
                serviceType: 'FIXED_INTERNET',
                id: 'TWOP0013',
                showUnit: true,
                isValue: true,
                isMonetary: false,
                isRange: false,
                isAsterisk: false,
              },
            ];
          },
          internalCategory: CATEGORY.POST_PAID_MOBILE,
          productId: 'TWOP0013',
          isYupProduct: false,
          externalProductCode: 'TWOP0013',
          productType: 'BUNDLE',
          categories: [
            CATEGORY.FOR_RULES_2_ND_HOME_PROMO_MANUAL,
            CATEGORY.FOR_RULES_FOR_129521_DISCOUNT,
            CATEGORY.FOR_RULES_125420_PROMO,
            CATEGORY.FOR_RULES_2_P_BUNDLES_FOR_649,
            CATEGORY.FOR_RULES_874_PROMO,
            CATEGORY.FOR_RULES_TLOS_WITH_TELENET_TV_1_0,
            CATEGORY.FOR_DISCOUNTS_874_PROMO,
            CATEGORY.FOR_RULES_FOR_110620_DISCOUNT,
            CATEGORY.FOR_RULES_PARTNER_DISCOUNT_EXCEPT_ONEUP,
            CATEGORY.FOR_RULES_453_EXTERNE_MEDEWERKERS_KORTING,
            CATEGORY.FOR_RULES_OFFERINGS_FOR_107800,
            CATEGORY.FOR_DISCOUNTS_FOR_120800_AND_120820,
            CATEGORY.FOR_DISCOUNTS_782_PROMO,
            CATEGORY.FOR_DISCOUNT_2_ND_HOME_PROMO_3_P_BUNDLES_INTERNET,
            CATEGORY.FOR_RULES_TLOS_WITH_SPEEDBOOST,
            CATEGORY.FOR_RULES_4_P_2_P_1_P_PLANS_WHERE_SAFESPOT_IS_PAYABLE,
            CATEGORY.FOR_RULES_2_P_BUNDLES,
            CATEGORY.FOR_DISCOUNT_121810_PROMO,
            CATEGORY.FOR_RULES_TOP_OFFERING_WITH_SERVICE_POLICIES,
            CATEGORY.FOR_RULES_WIGO_FOR_126941,
            CATEGORY.FOR_DISCOUNT_2_P_3_P_BUNDLES_INTERNET,
            CATEGORY.FOR_RULES_TV_ICONIC_FLOW_ONLY,
            CATEGORY.STAFF_DISCOUNT_FURIOUS_WITH_FIXED_LINE_NEW_OFFERING,
            CATEGORY.FOR_RULES_WIGOONEUP_BUNDLES,
            CATEGORY.FOR_DISCOUNTS_159_PROMO,
            CATEGORY.FOR_RULES_PARTNER_DISCOUNT,
            CATEGORY.FOR_DISCOUNTS_117200_PROMO,
            CATEGORY.FOR_RULES_115810_ONLY,
            CATEGORY.FOR_DISCOUNTS_132941_PROMO,
            CATEGORY.FOR_DISCOUNT_GROUP_DISCOUNT_MANUAL,
            CATEGORY.FOR_RULES_RES_DIGITAL_TV_AND_BUNDLES_WITH_DIGITAL_TV,
            CATEGORY.FOR_RULES_ALL_INTERNET_TV_WIGO_FOR_100650,
            CATEGORY.FOR_RULES_139331_PROMO,
            CATEGORY.FOR_RULES_649_ONLY,
            CATEGORY.FOR_RULES_TLOS_FOR_3_TB_FUP_INTERNET_SERVICE_POLICIES,
            CATEGORY.FOR_RULES_RES_BUNDLES,
            CATEGORY.FOR_DISCOUNTS_133331_PROMO,
            CATEGORY.FOR_SPONSOR_DISCOUNT_ALL_TLO_PRODUCTS,
            CATEGORY.FOR_DISCOUNT_FOR_107020_DISCOUNTS,
            CATEGORY.FOR_DISCOUNTS_26_PROMO,
            CATEGORY.FOR_RULES_ALL_INTERNET_TV_WIGO,
            CATEGORY.FOR_RULES_PRICE_REDUCTION_DURING_3_MONTHS,
            CATEGORY.FOR_RULES_FOR_112721_DISCOUNT,
            CATEGORY.FOR_RULES_FIXED_AND_BUNDLES_CATEGORY,
            CATEGORY.FOR_RULES_ALL_INTERNET_TELENET_TV_ICONIC_ALL_INTERNET_TELENET_TV_FLOW_ONE_FOR_X_ONEUP_FOR_X,
            CATEGORY.FOR_RULES_OFFERINGS_FOR_120531,
            CATEGORY.FOR_RULES_SUBSCRIPTION_CABLE_TV,
            CATEGORY.FOR_RULES_2_P_BUNDLES_INTERNET_IDTV,
            CATEGORY.FOR_RULES_FREE_ACTIVATION_PROMO,
            CATEGORY._2P_BUNDLE,
            CATEGORY.FOR_RULES_MULTI_DTV_PROMO,
            CATEGORY.FOR_RULES_2_P_1_P_PLANS_WHERE_SAFESPOT_IS_PAYABLE,
            CATEGORY.FOR_RULES_PARTNER_DISCOUNT_ONEUP_WITH_FIXED_LINE,
            CATEGORY.FOR_RULES_FOR_124951_DISCOUNT,
            CATEGORY.FOR_RULES_FOR_107020_DISCOUNTS,
            CATEGORY.FOR_RULES_DISCOUNTED_OFFERINGS_FOR_107800,
            CATEGORY.FOR_RULES_ALL_INTERNET_INTERNET_FIBER_200,
            CATEGORY.FOR_RULES_875_DISCOUNT,
            CATEGORY.FOR_RULES_139601_PROMO,
            CATEGORY.FOR_RULES_141321_INT_LINES,
            CATEGORY.FOR_RULES_9_PERSONEELSKORTING_TELENET,
            CATEGORY.POST_PAID_MOBILE,
          ],
          customerCategories: ['residential', 'eventdemo', PRODUCTION_TEST],
          subCategory: {},
          labelKey: ALL_INTERNET_TELENET_TVICONIC_LABEL,
          visible: true,
          weight: 370,
          services: [
            {
              serviceType: 'DTV',
              specifications: [
                {
                  labelKey: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                  visible: true,
                  weight: '20',
                  productType: 'DTV',
                  localizedContent: {
                    locale: 'nl',
                    name: WATCH_LIVE_AND_DELAYED_TV_ON_33_CHANNELS,
                  },
                },
                {
                  labelKey: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                  visible: true,
                  weight: '60',
                  productType: 'DTV',
                  localizedContent: {
                    locale: 'nl',
                    name: AUTOMATICALLY_SAVE_PROGRAMS_FOR_UP_TO_60_DAYS,
                  },
                },
                {
                  labelKey: WATCH_TV_BACK_UP_TO_7_DAYS,
                  visible: true,
                  weight: '40',
                  productType: 'DTV',
                  localizedContent: {
                    locale: 'nl',
                    name: WATCH_TV_BACK_UP,
                  },
                },
                {
                  labelKey: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                  visible: true,
                  weight: '50',
                  productType: 'DTV',
                  localizedContent: {
                    locale: 'nl',
                    name: THE_BEST_LOCAL_AND_INTERNATIONAL_SERIES_WITH_PLAY,
                  },
                },
              ],
              experience: {
                experienceType: 'ENTERTAINMENT',
              },
            },
            {
              serviceType: 'FIXED_INTERNET',
              specifications: [
                {
                  labelKey: SPEC_FIXEDINTERNET_VOLUME_DOWNLOAD_FUP,
                  unit: 'GB',
                  value: 'unlimited',
                  visible: true,
                  weight: '10',
                  productType: 'INTERNET',
                  localizedContent: {
                    locale: 'nl',
                    name: ONBEPERKT_SURFEN,
                  },
                },
                {
                  labelKey: SPEC_FIXEDINTERNET_SPEED_DOWNLOAD,
                  unit: 'Mbps',
                  value: '300',
                  visible: true,
                  weight: '40',
                  productType: 'INTERNET',
                  localizedContent: {
                    locale: 'nl',
                    name: DOWNLOADSNELHEID_TOT,
                  },
                },
                {
                  labelKey: SPEC_FIXEDINTERNET_MAILBOX_VOLUME,
                  unit: 'GB',
                  value: '5',
                  visible: true,
                  weight: '20',
                  productType: 'INTERNET',
                  localizedContent: {
                    locale: 'nl',
                    name: PER_MAILBOX,
                  },
                },
                {
                  labelKey: SPEC_FIXEDINTERNET_SPEED_UPLOAD,
                  unit: 'Mbps',
                  value: '20',
                  visible: true,
                  weight: '50',
                  productType: 'INTERNET',
                  localizedContent: {
                    locale: 'nl',
                    name: UPLOADSNELHEID_TOT,
                  },
                },
                {
                  labelKey: SPEC_FIXEDINTERNET_MAILBOX_INCLUDED,
                  value: '10',
                  visible: true,
                  weight: '60',
                  productType: 'INTERNET',
                  localizedContent: {
                    locale: 'nl',
                    name: 'mailboxen',
                  },
                },
              ],
              experience: {
                experienceType: 'SURF',
              },
            },
          ],
          apps: [],
          localizedContent: [
            {
              locale: 'en',
              name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
              logo: ALL_INTERNET_LOGO,
            },
            {
              locale: 'nl',
              name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
              logo: ALL_INTERNET_LOGO,
            },
            {
              locale: 'fr',
              name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
              logo: ALL_INTERNET_LOGO,
            },
          ],
          shortDescription: {
            localizedContent: {
              locale: 'nl',
              name: ALL_INTERNET_TELENET_TV,
            },
          },
          visibilityRules: {
            conditionalVisibility: false,
          },
          unlimited: false,
          eligibleForDiscount: false,
          priceType: RECURRENT_CHARGE,
          characteristics: {
            serviceCategory: 'FUP',
            productGroup: 'FMC',
            productSubGroup: INTERNET_DTV,
            productSegment: 'RMD',
            priceInclVat: 74,
            recipientsMandatory: false,
            esimAvailable: false,
          },
          usageBasedRatePlan: false,
          requiresInstallation: true,
          chars: [
            {
              key: 'internet_usage_limit',
              values: ['3000'],
              unit: 'GB',
            },
            {
              key: 'internet_usage_initial_threshold',
              values: ['2400'],
              unit: 'GB',
            },
            {
              key: 'internet_usage_alert_threshold',
              values: ['2700'],
              unit: 'GB',
            },
          ],
          isExternalContentPack: 'false',
          isEligibleForSettinglimits: false,
          isEligibleForAutoPause: false,
          isEligibleForPauseProfile: false,
          isFPBProduct: false,
          name: ALL_INTERNET_TELENET_TVICONIC_LABEL,
          logo: ALL_INTERNET_LOGO,
          usageLimits: {
            premiumService: {
              preferenceGroup: 'PremiumServices',
              limits: [
                {
                  communicationPreferenceType: 'OutBundleFraud',
                  communicationPreferenceTypeValue: 'NA',
                  isEditable: false,
                  values: [],
                },
                {
                  communicationPreferenceType: 'OutBundlePremiumSpendingLimit',
                  communicationPreferenceTypeValue: 'NA',
                  isEditable: false,
                  values: [],
                },
              ],
            },
          },
          usagenotifications: {
            mobile: [],
            internet: [
              {
                category: 'FUP',
                preferenceGroup: 'InternetFUP',
                threshold: [
                  {
                    communicationPreferenceType: 'Internet90',
                    communicationPreferenceTypeValue: '90',
                    isEditable: false,
                    values: [],
                  },
                  {
                    communicationPreferenceType: 'Internet100',
                    communicationPreferenceTypeValue: '100',
                    isEditable: false,
                    values: [],
                  },
                ],
              },
            ],
          },
          productConstituents: [
            {
              type: DTV_SIPADAN_TYPE,
              minCount: '0',
              maxCount: '1',
            },
            {
              type: DTV_SIPADAN_TYPE,
              minCount: '0',
              maxCount: '1',
            },
            {
              type: DTV_SIPADAN_TYPE,
              minCount: '0',
              maxCount: '1',
            },
            {
              type: DTV_SIPADAN_TYPE,
              minCount: '0',
              maxCount: '1',
            },
            {
              type: 'dtv[EOS]',
              minCount: '0',
              maxCount: '1',
            },
            {
              type: 'dtv[EOS]',
              minCount: '0',
              maxCount: '1',
            },
            {
              type: 'dtv[EOS]',
              minCount: '0',
              maxCount: '1',
            },
            {
              type: 'dtv[EOS]',
              minCount: '0',
              maxCount: '1',
            },
            {
              type: 'internet_line',
              minCount: '1',
              maxCount: '1',
            },
          ],
        },
        handsets: [],
        productType: 'bundle',
        addressId: '9165638478413166537',
        identifier: 'INTDTV000013364',
        hasIncludedOptions: false,
        options: [],
        hasExtraOptions: false,
        accountNumber: 501365353,
        label: 'All-Internet + Telenet TV iconic',
        specUrl: 'https://api.int.telenet.be/omapi/public/product/TWOP0013',
        status: 'ACTIVE',
        price: {
          taxInclPrices: {},
        },
        isUnderMove: false,
        locationId: '9167320887513186766',
        showModemUpgradeBanner: false,
      },
    ] as unknown as Product[];
  }
}
