export enum InstallationTypeEnum {
  TYPE_HOME_DELIVERY = 'Home Delivery',
  TYPE_PICKUP_DELIVERY = 'Pick-up Delivery',
  TYPE_COMFORT_INSTALL = 'Comfort Install',
  TYPE_SELF_INSTALL = 'Self Install',
  NORMALIZED_TYPE_HOME_DELIVERY = 'home-delivery',
  NORMALIZED_TYPE_PICKUP_DELIVERY = 'pick-up-delivery',
  NORMALIZED_TYPE_COMFORT_INSTALL = 'comfort-install',
  NORMALIZED_TYPE_BUSINESS_INSTALL = 'business-install',
  NORMALIZED_TYPE_SELF_INSTALL = 'self-install-at-home',
  TYPE_CHOSEN_DELIVERY = 'Chosen Delivery',
  TYPE_SIM_CARD_DELIVERY = 'SIM Card Delivery',
  TYPE_MODEM_COMPATIBILITY = 'installation-type-modem-compatibility',
  INSTALLATION_BUSINESS = 'Business Install',
}
