export enum ProductStatusEnum {
  ADD = 'ADD',
  ADDED = 'ADDED',
  MODIFY = 'MODIFY',
  ACTIVE = 'ACTIVE',
  NOT_ACTIVE = 'NOT_ACTIVE',
  ACTIVATION_PASSED_PONR = 'ACTIVATION_PASSED_PONR',
  DISCONNECT = 'DISCONNECT',
  DISCONNECTED = 'DISCONNECTED',
  COMPLETED = 'COMPLETED',
  SUSPENDED = 'SUSPENDED',
  DISCONNECTION_IN_PROGRESS = 'DISCONNECTION_IN_PROGRESS',
}
