variables:
  CLIENT_PROJECT: marketing-mfe
  LEANIX_APPLICATION_NAME: marketing
  GITOPS_DEPLOY_FOLDER_NAME: marketing
  CLIENT_E2E: marketing-mfe-e2e
  TZ: 'Europe/Brussels' #Setting the environment Time Zone

include:
  - local: '/tools/gitlab/base/application.yml'

test:app:
  extends: .test:app
  rules:
    - when: always

build:app:
  extends: .build:app

build:storybook:
  extends: .build:storybook

push-to-harbor:
  extends: .push-to-harbor

component-test:app:
  extends: .component-test:app

sonar:app:
  needs:
    - test:app
    - component-test:app
  extends: .sonar:app

gitops-deploy-dev:
  extends: .gitops-deploy-dev

gitops-deploy-upgrade:
  extends: .gitops-deploy-upgrade

gitops-deploy-stage:
  extends: .gitops-deploy-stage

gitops-deploy-prod:
  extends: .gitops-deploy-prod

tag-stage-candidate:
  extends: .tag-stage-candidate

tag-prod-candidate:
  extends: .tag-prod-candidate

patch-stage:
  extends: .patch-stage

patch-prod:
  extends: .patch-prod
