variables:
  CLIENT_PROJECT: care-service-cases-mfe
  LEANIX_APPLICATION_NAME: engagement
  CLIENT_E2E: care-service-cases-mfe-e2e
  GITOPS_DEPLOY_FOLDER_NAME: care-service-cases

include:
  - local: '/tools/gitlab/base/application.yml'

test:app:
  extends: .test:app
  rules:
    - when: always

e2e:app:
  extends: .e2e:app
  rules:
    - when: always

build:app:
  extends: .build:app

build:storybook:
  extends: .build:storybook

push-to-harbor:
  extends: .push-to-harbor

component-test:app:
  extends: .component-test:app

sonar:app:
  extends: .sonar:app
  needs:
    - test:app
    - component-test:app

gitops-deploy-dev:
  extends: .gitops-deploy-dev

tag-stage-candidate:
  extends: .tag-stage-candidate

tag-prod-candidate:
  extends: .tag-prod-candidate

gitops-deploy-stage:
  extends: .gitops-deploy-stage

gitops-deploy-upgrade:
  extends: .gitops-deploy-upgrade

gitops-deploy-prod:
  extends: .gitops-deploy-prod

patch-stage:
  extends: .patch-stage

patch-prod:
  extends: .patch-prod

integration-test-int:
  stage: deploy to dev (dvp, int, sup)
  inherit:
    variables: false
  trigger:
    project: css/css-frontend/selfcare/test-automation/cypress-integration-tests
    branch: main
  variables:
    TELENET_ENV: int
    TEST_TYPE: service-cases
    SOURCE: service-cases
  needs:
    - gitops-deploy-dev
  only: !reference [.allowed-branches-dev-deploy]
  when: on_success
  allow_failure: true
